name: med_words
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  ###
  flutter_bloc: ^8.1.6
  go_router: ^14.2.0
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf
    - family: BarlowM
      fonts:
        - asset: assets/fonts/Barlow-Medium.ttf
    - family: BarlowB
      fonts:
        - asset: assets/fonts/Barlow-Bold.ttf
    - family: BarlowI
      fonts:
        - asset: assets/fonts/Barlow-Italic.ttf
